const sb = supabase.createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY);
let albums=[], photos=[], activeAlbum='Semua', filtered=[], currentIndex=0, user=null;

const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function requireConfig(){if(!window.SUPABASE_URL||window.SUPABASE_URL.includes('PASTE_')||!window.SUPABASE_ANON_KEY||window.SUPABASE_ANON_KEY.includes('PASTE_')){toast('Isi config.js dengan data Supabase terlebih dahulu');return false}return true}
async function init(){if(!requireConfig())return;const r=await sb.auth.getSession();user=r.data.session?.user||null;updateAuthUI();await loadAlbums();await loadPhotos();sb.auth.onAuthStateChange(async(_,s)=>{user=s?.user||null;updateAuthUI()})}
function updateAuthUI(){$$('.admin-only').forEach(e=>e.classList.toggle('hidden',!user));$('#loginBtn').classList.toggle('hidden',!!user);$('#logoutBtn').classList.toggle('hidden',!user)}
function $$(s){return [...document.querySelectorAll(s)]}
async function loadAlbums(){const {data,error}=await sb.from('albums').select('*').order('created_at');if(error){toast(error.message);return}albums=data||[];renderTabs()}
async function loadPhotos(){const {data,error}=await sb.from('photos').select('*').order('created_at',{ascending:false});if(error){toast(error.message);return}photos=data||[];render()}
function renderTabs(){const el=$('#albumTabs');el.innerHTML='';['Semua',...albums.map(a=>a.name)].forEach(a=>{const wrap=document.createElement('div');wrap.className='tab-wrap';const b=document.createElement('button');b.className='tab '+(activeAlbum===a?'active':'');b.textContent=a;b.onclick=()=>{activeAlbum=a;render()};wrap.append(b);if(a!=='Semua'&&user){const d=document.createElement('button');d.className='tab-delete';d.textContent='×';d.onclick=()=>deleteAlbum(a);wrap.append(d)}el.append(wrap)})}
function render(){renderTabs();const q=$('#search').value.toLowerCase();filtered=photos.filter(p=>(activeAlbum==='Semua'||p.album_name===activeAlbum)&&p.name.toLowerCase().includes(q));$('#empty').classList.toggle('hidden',filtered.length>0);const g=$('#gallery');g.innerHTML='';filtered.forEach((p,i)=>{const c=document.createElement('div');c.className='photo';c.innerHTML=`<img src="${p.public_url}" alt="${esc(p.name)}" loading="lazy"><div class="label">${esc(p.name)}</div>`;c.onclick=()=>openViewer(i);g.append(c)})}
async function uploadFiles(files){if(!user){toast('Login admin untuk mengunggah foto');return}let album=activeAlbum==='Semua'?albums[0]?.name:null;if(!album){toast('Buat album terlebih dahulu');return}for(const f of files){if(!f.type.startsWith('image/'))continue;const safe=crypto.randomUUID()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${user.id}/${safe}`;const up=await sb.storage.from('photos').upload(path,f,{contentType:f.type,upsert:false});if(up.error){toast(up.error.message);continue}const {data:pub}=sb.storage.from('photos').getPublicUrl(path);const ins=await sb.from('photos').insert({name:f.name,album_name:album,storage_path:path,public_url:pub.publicUrl});if(ins.error)toast(ins.error.message)}await loadPhotos();toast('Foto berhasil diunggah')}
async function createAlbum(){if(!user){toast('Login admin terlebih dahulu');return}const n=$('#albumName').value.trim();if(!n)return;const r=await sb.from('albums').insert({name:n});if(r.error){toast(r.error.message);return}$('#albumDialog').classList.add('hidden');$('#albumName').value='';await loadAlbums();activeAlbum=n;render();toast('Album dibuat')}
async function deleteAlbum(name){if(!confirm(`Hapus album "${name}" dan semua fotonya?`))return;const list=photos.filter(p=>p.album_name===name);for(const p of list){await sb.storage.from('photos').remove([p.storage_path]);await sb.from('photos').delete().eq('id',p.id)}const r=await sb.from('albums').delete().eq('name',name);if(r.error)toast(r.error.message);if(activeAlbum===name)activeAlbum='Semua';await loadAlbums();await loadPhotos();toast('Album dihapus')}
function openViewer(i){currentIndex=i;showViewer()}function showViewer(){if(!filtered.length)return;const p=filtered[currentIndex];$('#viewerImg').src=p.public_url;$('#viewerName').textContent=p.name;$('#modal').classList.remove('hidden')}function closeViewer(){$('#modal').classList.add('hidden')}
async function deleteCurrent(){if(!user)return;const p=filtered[currentIndex];if(!p||!confirm(`Hapus "${p.name}"?`))return;await sb.storage.from('photos').remove([p.storage_path]);const r=await sb.from('photos').delete().eq('id',p.id);if(r.error)toast(r.error.message);closeViewer();await loadPhotos();toast('Foto dihapus')}
$('#loginBtn').onclick=()=>$('#loginDialog').classList.remove('hidden');$('#cancelLogin').onclick=()=>$('#loginDialog').classList.add('hidden');
$('#loginSubmit').onclick=async()=>{const email=$('#email').value.trim(),password=$('#password').value;const r=await sb.auth.signInWithPassword({email,password});if(r.error){$('#loginMessage').textContent=r.error.message;return}$('#loginDialog').classList.add('hidden');toast('Login berhasil')};
$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();toast('Berhasil keluar')};$('#addAlbumBtn').onclick=()=>$('#albumDialog').classList.remove('hidden');$('#cancelAlbum').onclick=()=>$('#albumDialog').classList.add('hidden');$('#saveAlbum').onclick=createAlbum;
$('#photoInput').onchange=e=>{if(e.target.files.length)uploadFiles([...e.target.files]);e.target.value=''};$('#search').oninput=render;
$('#closeModal').onclick=closeViewer;$('#deletePhoto').onclick=deleteCurrent;$('#prevPhoto').onclick=()=>{currentIndex=(currentIndex-1+filtered.length)%filtered.length;showViewer()};$('#nextPhoto').onclick=()=>{currentIndex=(currentIndex+1)%filtered.length;showViewer()};
document.addEventListener('keydown',e=>{if($('#modal').classList.contains('hidden'))return;if(e.key==='Escape')closeViewer();if(e.key==='ArrowLeft')$('#prevPhoto').click();if(e.key==='ArrowRight')$('#nextPhoto').click()});
window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('drop',e=>{e.preventDefault();if(e.dataTransfer.files.length)uploadFiles([...e.dataTransfer.files])});
init();
